name: Create Release

on:
  workflow_call:
    inputs:
      prerelease:
        description: A flag for creating a release as a prerelease
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Extract version
        id: extract_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set tag
        id: set_tag
        run: |
          TAG="v${{ steps.extract_version.outputs.version }}"
          TAG1="v"
          echo "tag=$TAG1" >> $GITHUB_OUTPUT

      - name: Check tag
        if: ${{ !startsWith(steps.set_tag.outputs.tag, 'v') || steps.set_tag.outputs.tag == 'v' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("An invalid tag was generated: ${{ steps.set_tag.outputs.tag }"}

      - name: Create release
        run: |
          echo "Release ${{ steps.set_tag.outputs.tag }}"
          echo "Prerelease: ${{ inputs.prerelease }}"
        #uses: softprops/action-gh-release@v1
        #with:
        #  prerelease: ${{ inputs.prerelease }}
        #  tag_name: ${{ steps.set_tag.outputs.tag }}
        #  token: ${{ secrets.GITHUB_TOKEN }}
