name: Push to main branch

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  bump-version-check:
    runs-on: ubuntu-latest
    outputs:
      is-bump-version-author: ${{ steps.set-output.outputs.is-bumper-version-author }}
    steps:
      - name: Set flag for bump version author
        id: set-output
        run: |
          flag=${{ contains(github.event.head_commit.message, 'bump-version[bot]@users.noreply.github.com') }}
          echo "is-bumper-version-author=$flag" >> $GITHUB_OUTPUT

  create-version-bump-pr:
    runs-on: ubuntu-latest
    needs: [bump-version-check]
    if: ${{ needs.bump-version-check.outputs.is-bump-version-author == 'false' }}
    steps:
      - name: create-version-bump-pr-test
        run: echo "Create version bump pr"

  create-prerelease-and-publish:
    runs-on: ubuntu-latest
    needs: [bump-version-check]
    if: ${{ needs.bump-version-check.outputs.is-bump-version-author == 'true' }}
    steps:
      - name: create-prerelease-and-publish-test
        run: echo "Create prerelease and publish

