name: prerelease
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags')
        with:
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
