name: Create Prerelease and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

env:
  run-jobs: ${{ contains( github.event.head_commit.message, 'bump-version[bot]@users.noreply.github.com') }}

jobs:
  create-prerelease:
    if: ${{ run-jobs }}
    uses: ./.github/workflows/create-release.yml
    with:
      prerelease: true

  publish-package:
    needs: [create-prerelease]
    if: ${{ run-jobs && !failure() && !cancelled() }}
    uses: ./.github/workflows/publish-package.yml
