name: Create Prerelease and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  run-jobs-check:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.set-output.outputs.run }}
    steps:
      - name: Set flag for running jobs
        id: set-output
        run: |
          flag=${{ contains( github.event.head_commit.message, 'bump-version[bot]@users.noreply.github.com') }}
          echo "run=$flag" >> $GITHUB_OUTPUT

  test-echo:
    needs: [run-jobs-check]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo ${{ needs.run-jobs-check.outputs.run }}
          echo ${{ needs.run-jobs.check.outputs.run == true }}
          echo ${{ needs.run-jobs.check.outputs.run == false }}
          

  create-prerelease:
    needs: [run-jobs-check]
    if: ${{ needs.run-jobs-check.outputs.run }}
    uses: ./.github/workflows/create-release.yml
    with:
      prerelease: true

  publish-package:
    needs: [run-jobs-check, create-prerelease]
    if: ${{ needs.run-jobs-check.outputs.run && !failure() && !cancelled() }}
    uses: ./.github/workflows/publish-package.yml
