name: prerelease
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Extract version
        run: echo "::set-output name=version::$(node -p \"require('./package.json').version\")"

      - name: Set version tag
        id: set_tag
        run: echo "::set-output name=tag::v${{steps.extract_version.outputs.version}}"

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(steps.set_tag.outputs.tag, 'v' )
        with:
          prerelease: true
          tag_name: ${{ steps.set_tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
